### ISSUE TITLE
VDM: Request for Euro Inland blue sign information.

### ISSUE THREAD

**Issue by Hakansv** [SignalK/signalk-parser-nmea0183#165]
From VDM sentence the info about the blue sign is essential for inland traffic. Either present and set to 1 = "No" or 2= "Yes" or not present.
A corresponding SK path is out of our scope but Navigation.Inland.Blue_sign: Value 1 or 2  ??
If Inland is set in message 8 the presences of the above path would be obvious as an indication for an Inland ship.

From OCPN code VDM message 1,2 or 3: 
//    Capture Euro Inland special passing arrangement signal ("stbd-stbd")
 ```
           ptd->blue_paddle = bstr->GetInt( 144, 2 );
            ptd->b_blue_paddle = ( ptd->blue_paddle == 2 );             // paddle is set
```
From here: [AIVDM spec. ](https://gpsd.gitlab.io/gpsd/AIVDM.html#_type_18_standard_class_b_cs_position_report)
Riverine and inland navigation systems conforming to [INLAND] designate this field "Blue Sign" with the following enumerated values:
![bild](https://user-images.githubusercontent.com/7202854/75070324-446cf980-54f3-11ea-837c-da6fc713695c.png)

Since VDM message 3: 144, 2 can be used also for other designations the following info would be valuable as well:
VDM message 8:
This how it's [parsed in OCPN:](https://github.com/OpenCPN/OpenCPN/blob/a69cde47122c2750adad6025045ac055f3d1323b/src/AIS_Decoder.cpp#L2020)
```
case 8:                                    // Binary Broadcast
        {
            int dac = bstr->GetInt( 41, 10 );
            int fi = bstr->GetInt( 51, 6 );
            if( dac == 200 )                  // European inland
                    {
                if( fi == 10 )              // "Inland ship static and voyage related data"
                        {
                    ptd->b_isEuroInland = true;
```
In message 8 also other inland properties would be informative but the blue sign is of outmost priority.

**Comment by sbender9** [comment]
This is not supported in the decoder we use: https://github.com/fulup-bzh/GeoGate/tree/master/encoder

**Comment by Hakansv** [comment]
@sbender9 
I understand but is somewhat disappointed. Is there a possibility to request this support from your decoder?
As mentioned this is crucial for the EU inland traffic. In fact OCPN is approved for ships using "Inland ECDIS V2.3" based on our capability to support it's rules for what to show and how it interacts with the crew. It may take some time before barges adapt SignalK but N2k would become more common also here so it will not take long I think.

**Comment by Hakansv** [comment]
Attached is a file where the use of message 8 "European Inland are set ("200") and two of them have the blue sign to OFF and two where the blue sign is ON.
The shot shows how it's shown in OCPN. (Ships not sailing acc. to Inland ECDIS gets another, round, symbol in OCPN Inland mode)

```
Examples of ships sailing according to Inland ECDIS V2.3
The European Inland is used. The blue sign set to Off
!AIVDM,1,1,,A,139n@m000pPMTL2MUGmECDLvR53P,0*67
!AIVDM,1,1,,A,133ss2gP1IPLHkDMb3MK2gw0R0T6,0*19

The European Inland is used. The blue sign set to ON
!AIVDM,1,1,,A,339n@`P00`PLt=`M`H6n0lq72000,0*71
!AIVDM,1,1,,B,339n@`PP@jPLtAtM`GQUt4cS211P,0*59

```
[Blue_flags.txt](https://github.com/SignalK/signalk-parser-nmea0183/files/4243561/Blue_flags.txt)


![bild](https://user-images.githubusercontent.com/7202854/75137468-f705ad80-56e7-11ea-8e5f-d3f5c1665b0d.png)

**Comment by sbender9** [comment]
@Hakansv do you have any idea how this is done with NMEA2000?

**Comment by Hakansv** [comment]
No sorry. I've so far very limited experiences from N2k. There would be some corresponding messaging system as the NMEA0183 but I've not seen any of the proprietary standard for that. But there are AIS transponders direct connected to a N2k bus as you may know. The CanBoat people may know more. I'll ask around..

**Comment by sbender9** [comment]
Can you join us on Slack? http://slack-invite.signalk.org/

I'd like to have a private conversation with you there.

**Comment by Hakansv** [comment]
The blue flag indicator is there. But a Inland traffic flag would also be there. Compare [this manual:](http://www.3wavesenergy.com/images/Manuals/Simrad/V5035_OM_EN_988-10838-002_w.pdf) page 28 , 37, 39 and more for Inland mode.

![bild](https://user-images.githubusercontent.com/7202854/75224369-a7d38180-57a8-11ea-8db3-a29af33cc68a.png)

**Comment by marcus-aa** [comment]
Hi,

There is probably no defined N2K PGN for inland AIS. The Simrad manual does not list any in the "supported PGNs" section. But someone with access to the NMEA PGN database need to verify this.

The transmission of AIS over N2K has it's limitations. AIS has a large number of expansion possibilities, including bits reserved fo future use, binary payload messages not yet defined and even entirely new messages. 

With NMEA0183 this is easy, as the entire VDL payload is just put un-decoded in the AIVDM message, even for messages in the future that are not yet defined, as long as they pass some sanity checks. Only the decoding side needs to be updated to understand this new payload.

Not so with N2K. From the start, NMEA has required all N2K PGNs to be parametric, i. e. broken down and defined for every bit of data transmitted. While this is good to keep a high level of standardization, it becomes problematic for such complex data as AIS.

Every time the AIS standard is amended, new PGNs has to be designed, proposed and approved by NMEA members. Then they should be implemented (hopefully) by manufacturers. But the interest in changing and re-certifying existing equipment is very low due to cost.

The problem is also that it requires work and changes on 3 parts, the NMEA to define the PGNs, the AIS receiving device to decode VDL and encode PGNs, and the data user (plotter/chart system etc) to decode the PGNs and use the data... This will take many year, if it ever materializes.

N2K PGNS are always "behind" the AIS standard for this reason and will never really catch up.

AIS manufacturers have suggested to NMEA AIS-WG to adopt an "AIS undefined" PGN where such data could go that there is (yet) no PGN for, in the same way the AIVDM message works. Then all future enhancements of AIS would not be lost over N2K. Only the user of the data would need to know what it contains. But that would mean a change from the parametric principle and no decision has been made about this yet.

So, there is NO way to guarantee that all received AIS data is passed over N2K, its is more of a guarantee that it is not.

There was similar problems when the AIS ClassB CS standard emerged and messages were changed to keep them shorter and more suitable for CS transmission. Some manufacturers adopted proprietary messages and it took quite some time to align the equipment again once the new PGNs were published.

https://www.panbo.com/ais-over-nmea-2000-the-shame-sheet/


AIS over N2K is not allowed for wheelmarked systems on ship bridges....

**Comment by afischerdev** [comment]
The ggencoder already delivers a part of message 8:
dac = 200 fid = 10 comes with European Vessel ID, length, width, draught and ship type ERI 
all other message 8 reports are ignored

**Comment by Hakansv** [comment]
@afischerdev 
OK, very good. Than it's for the SK part to find out a suitable path and the OCPN part to adapt to that. 
Next is the info in VDM message 1, 2 or 3 at:  (OCPN use:) blue_paddle = bstr->GetInt( 144, 2 );
can be used for that. 
OCPN can use the combination "EU Inland == Set and the message 3 info 0/1/2 to detect:
1: If the blue sign is used.
2: The blue sign is ON or OFF.

Would it be possible for you to add also the blue sign info from VDM message 1,2,3 144, 2?
Thanks
Håkan

**Comment by Hakansv** [comment]
@marcus-aa 
Thanks for the valuable information. Appreciated!
Could a conclusion be that the blue sign info is not relevant for a N2k network?
The info is not of any interest for others than EU Inland ships. And if I read you correct a AIS would never be connected via a N2k bus on a (Inland ECDIS) ship? They are obliged to use NMEA0183 for AIS. 
Is that info verified?

If so we are up to date for SignalK once the blue sign is parsed from sentence VDM via ggencoder to a SK path.

**Comment by afischerdev** [comment]
@Hakansv 
The blue sign is already done.
It comes as 'smi' (Maneuver Indicator) with the messages 1,2,3

**Comment by Hakansv** [comment]
@afischerdev  
Thanks.
So then the we have the "dac" & "fid" from message 8 and "smi" from message 1,2,3.
Would be suitable. @sbender9, what paths can we get out of this?

**Comment by marcus-aa** [comment]
> @marcus-aa
> Could a conclusion be that the blue sign info is not relevant for a N2k network?

As has emerged from the discussion, it may be enough to look for the DAC and then the Maneuver indicator, which should be available in PGN129038, so fully possible using N2K. 

>  And if I read you correct a AIS would never be connected via a N2k bus on a (Inland ECDIS) ship? They are obliged to use NMEA0183 for AIS.
> Is that info verified?

Well at least not on a IMO/SOLAS ship, the IMO "GUIDELINES FOR THE INSTALLATION OF A SHIPBORNE AUTOMATIC IDENTIFICATION SYSTEM (AIS) " says

```
3.3 Display system
If there is navigational equipment capable of processing and displaying AIS information such as
ECDIS, radar or an integrated system available on board the ship, the AIS Class A mobile system
may be connected to that system via the AIS Presentation Interface (PI). The PI (input/output)
should meet the requirements of IEC 61162-2. 
```
and 

```
4.1 External Sensors
The AIS has interfaces (configurable as IEC 61162-1 or 61162-2) for position, heading and rate of
turn (ROT) sensors.
```

IEC 61162-1 is NMEA0183 and 61162-2 is NMEA0183-HS (38400bps)

N2K is IEC 61162-3

https://www.e-navigation.nl/sites/default/files/IMO_SN_Circ227.pdf
https://en.wikipedia.org/wiki/IEC_61162

BTW, Solas equipment is now going straight to Ethernet using IEC 61162-460:2015(E) standard.

NMEA has proposed PGNs over Ethernet, called OneNet for leisure crafts.... 
https://www.nmea.org/content/STANDARDS/OneNet

**Comment by Hakansv** [comment]
Thanks Marcus
Let's see what the team can get out the here collected knowledge. I think we now have info enough to finalize this issue?

**Comment by sbender9** [comment]
@Hakansv can you get me some test messages for this?

**Comment by afischerdev** [comment]
@sbender9 
The ggencoder contains a test sample for message 8 (msg8_200_10)
and one for a virtual sign (msg21)

**Comment by sbender9** [comment]
@afischerdev thanks!

**Comment by Hakansv** [comment]
@sbender9 
Look some posts up from yesterday

**Comment by sbender9** [comment]
@Hakansv I think #170 will do it?

**Comment by sbender9** [comment]
I've added the specialManeuver indicator for N2K messages. Looks like that's the best we can do there for now.

**Comment by Hakansv** [comment]
@sbender9 
Thanks a lot to Scott and all others involved. I do think this will do.
Once available as an SK update or npm I'll test and report back
