### ISSUE TITLE
Conversion precision

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-parser-nmea0183#36]
Conversion is naive and does not consider significant numbers.

If the converter takes 6.11 knots (N) or 11.31 km/h and converts that to 3.143255556 m/s we’re ‘inventing’ precision.

 One way to fix this is for the converter to automatically remember source precision (0.01 km/h == 0.028 m/s) so round to that.

3.143255556 - (3.143255556 % 0.027778) = 3.1414

**Comment by philgutowski** [comment]
So, I'm not one of the most mathematically inclined, but some googleing on the subject of unit conversion with precision has presented a few different ways to solve this.  @tkurki, you're suggestion is excellent except that to identify the initial precision still requires doing a unit conversion (which can introduce more false numbers), correct?  Unless we reference a table of conversion precisions, this would be difficult.  Am I missing something?

Obviously a short term fix could be just to round to a select number of decimal places based on the converted unit.  We could use `toPrecision()` for that.

This could also be a useful.  https://www.npmjs.com/package/js-quantities#rounding
But, I would imagine we want to be careful how many new libraries we are introducing.

**Comment by fabdrol** [comment]
An easy solution using parseFloat and toFixed:
```javascript
function(n, precision) {
  return parseFloat(n.toFixed(precision))
}
```

**Comment by fabdrol** [comment]
```javascript
let n = .2 + .1 // 0.30000000000000004, JS quirk
let precision = 1
n = function normalisePrecision (n, precision)
```

**Comment by tkurki** [comment]
I will try to summon @canboat to help out here, since I don't have a good solution. It isn't nowhere as simple as to just do toFixed.

I guess a real, practical question is that given for example 180.0 degrees how do we figure out how many decimal values we should output.

180.0 really means that the value is between 179.5 degrees and 180.5 degrees, error range of 0.1 degrees. 

In radians that is approximately 3.141592654, between approx 3.140719989 and 3.14246532 radians. So in this sample the second 1 may be off - we don't know. 

We can truncate/round that to 3.14, based on the fact that the degree error range is approx 0.001745329 in radians. 

But if we do that we are really expanding the absolute error range, as now the error range is 0.01 radians, equivalent of 0.5729577951 degrees.

This didn't even take into account any implementation dependent rounding errors.

I am willing to let this issue rest until somebody comes up with a clean solution, as the impact is really negligible as I see it.

**Comment by canboat** [comment]
let n = .2 + .1 // 0.30000000000000004, JS quirk

... is NOT a JS quirk. It is a direct consequence of using binary floating point number representation. Since a binary floating point number does not represent an exact decimal value there are many cases where there is a conversion error when you convert from the one to the other. 0.2 and 0.1 are both values that cannot be represent exactly in binary. 0.1 is 00111101110011001100110011001101 and when cast back to a double that becomes 0.10000000149011612. See http://www.h-schmidt.net/FloatConverter/IEEE754.html

One way to fix this would be to use a library that represents numbers in a way like `BigDecimal` does in Java. A quick search finds several JS libraries, for instance https://github.com/MikeMcl/decimal.js/ .

@tkurki is right that it is quite easy to change the error range inadvertently. Even worse, the error range is different for different sources. For instance NMEA 0183 transmits angles in 0.1 degree precision whilst NMEA 2000 transmits angles with a precision of 0.0001 radians, or about 0.006 degrees. Not sure about NMEA 0183 but in NMEA 2000 at least there is also another problem in that some values can be transmitted with multiple precisions. For instance rotation can be represent in 0.001/32 radians/s (f.i. PGN 127237 "Heading/Track Control" and in 0.0000001/32 radians/s (PGN 127251 "Rate of Turn").

Now the fact that the NMEA 2000 PGN specifies such large precision (for rate of turn for example) doesn't mean that the data is actually that precise. For instance, my RC42 compass transmits values for that hires PGN that are values that seem to be a multiple of some value near to 54175

Value | Multiple of 54175 
--------|------------------------
54175 | 1 
108908 | 2,0103 
163083 | 3,0103 
217817 | 4,0206 

So it seems clear that the actual quantisation of the heading rotation generated by a RC42 is around 54175 of the minimal precision allowed by NMEA 2000. But there is no way in NMEA 2000 to represent that.

So all simplistic routines or conversions will have corner cases where the approach breaks down.
The "most correct" approach that I see is that we keep a precision with every numeric value. Since the precision is different from every source it is probably easiest to just keep it with the number itself. A really precise implementation could even store knowledge about the transmitting device. In fact, a "smart" Signal K device might even just observe the data stream and infer the quantisation error.

Another approach is to just ignore it and let clients decide how much precision they want to use or display.

And the third approach is that we allow customers to set precision on their data themselves, possibly with a good guess by the data model. A client interested in full precision can then say it wants all detail whilst a UI client could ask for nicely rounded numbers.

**Comment by fabdrol** [comment]
@canboat I didn't know that, thanks for the background. 

For this simple 0183 parser anything beyond @tkurki's original issue might be out of scope: if a value comes in with two decimals, the resulting converted value should have no more than two decimals. Rounding to that should be sufficient, I feel.

**Comment by tkurki** [comment]
@fabdrol that won't work, it varies by conversion. 

If you convert lightyears to kilometers  rounding off to the same number of decimal places will be meaningless.

Closing, as I don't see a workable solution.
